// src/app/layout.tsx
import Navigation from './components/Navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />    {/* Global Nav goes here */}
        {children}        {/* Page content goes here */}
      </body>
    </html>
  );
}